Repository splintered-reality/py_trees_ros, pull requests merged in 2019-02, with the labels that each got.

#48 #WIP Decorators as Behaviour
  .gitignore
  py_trees_ros/conversions.py
Labels: component:trees, type:enhancement

#50 Stonier/kinetic melodic sync
  .gitignore
  CHANGELOG.rst
  package.xml
  py_trees_ros/conversions.py
Labels: component:infra, type:enhancement

#52 [mock] drop termcolor dependency
  package.xml
  py_trees_ros/__init__.py
  py_trees_ros/mock/led_strip.py
  setup.cfg
Labels: component:mocks, type:enhancement

#58 [mock] start stripping out mock components
  .pydevproject
  .settings/org.eclipse.core.resources.prefs
  graveyard/building_blocks.rst
  graveyard/examples.rst
  graveyard/launchers.rst
  graveyard/modules.rst
  graveyard/patterns.rst
  graveyard/terminology.rst
  package.xml
  py_trees_ros/demos/talker-latched.py
  py_trees_ros/demos/testies.py
  py_trees_ros/launch/__init__.py
  py_trees_ros/launch/tutorial_one.py
  py_trees_ros/mock/battery.py
  py_trees_ros/mock/dashboard.py
  py_trees_ros/mock/gui/__init__.py
  py_trees_ros/mock/gui/dashboard_group_box.py
  py_trees_ros/mock/gui/dashboard_group_box.ui
  py_trees_ros/mock/gui/gen.bash
  py_trees_ros/mock/gui/main_window.py
  py_trees_ros/mock/gui/main_window.qrc
  py_trees_ros/mock/gui/main_window.ui
  py_trees_ros/mock/gui/main_window_rc.py
  py_trees_ros/mock/gui/reconfigure_group_box.py
  py_trees_ros/mock/gui/reconfigure_group_box.ui
  py_trees_ros/mock/gui/tuxrobot.png
  py_trees_ros/mock/led_strip.py
  py_trees_ros/programs/latched_echo.py
  py_trees_ros/utilities.py
  setup.py
Labels: component:mocks, type:feature

#61 [actions] remove redundant print
  py_trees_ros/actions.py
Labels: component:behaviours, type:bug
